feat: add changes according HW 3
NatalliaSh/notes-app pull request #3
Opened 2023-11-29 15:07 UTC by NatalliaSh

2023-11-29 15:55 UTC, tagizade-samir requested changes

2023-11-29 15:55 UTC, tagizade-samir commented on src/components/note/note-for-personal-page.tsx
> +  console.log(background)
Лишняя консолька

2023-11-29 15:55 UTC, tagizade-samir commented on src/components/toast/success-toast-view/index.tsx
> +export * from './success-toast-view'
Тут не ошибка в принципе, но такие файлы можно оставлять с расширением .ts, .tsx нужно только когда мы используем разметку внутри файла

2023-11-29 15:55 UTC, tagizade-samir commented on src/services/router.tsx
> +        element: <PublicNotesPage />,
Тут не совсем так, потому что все экраны, кроме экрана логина должны быть protected, мы попадаем туда только после авторизации

2023-11-30 13:26 UTC, NatalliaSh commented on src/components/note/note-for-personal-page.tsx
> +  console.log(background)
Исправила, спасибо!

2023-11-30 13:26 UTC, NatalliaSh commented on src/components/toast/success-toast-view/index.tsx
> +export * from './success-toast-view'
Спасибо

2023-11-30 14:09 UTC, NatalliaSh commented on src/services/router.tsx
> +        element: <PublicNotesPage />,
Спасибо, поправила

2023-11-30 20:25 UTC, tagizade-samir approved these changes

2023-12-04 08:02 UTC, merged